[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qsarcons"
version = "1.1.4"
description = "Molecular property prediction with genetic consensus"
readme = { file = "README.rst", content-type = "text/x-rst" }
license = { text = "MIT" }
authors = [
  { name = "Dmitry Zankov", email = "dvzankov@gmail.com" }
]

dependencies = [
        "psutil",
        "rdkit",
        "molfeat",
        "scikit-learn",
        "xgboost",
        "huggingface_hub",
        "pytest"
]

[tool.setuptools.packages.find]
where = ["."]
